[project]
name = "autonomous_data_collection"
version = "0.1.0"
description = "autonomous_data_collection using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[file-processing,litellm,tools]>=1.15.11,<2.0.0",
    "exa-py",
]

[project.scripts]
autonomous_data_collection = "autonomous_data_collection.main:run"
run_crew = "autonomous_data_collection.main:run"
train = "autonomous_data_collection.main:train"
replay = "autonomous_data_collection.main:replay"
test = "autonomous_data_collection.main:test"
run_with_trigger = "autonomous_data_collection.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
project_id = "42bbe57b-6543-4729-8545-2b481cb8ed9b"

[tool.uv]
override-dependencies = ["litellm<=1.82.6"]
